version: 0.2
phases:
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket pipeline-artifacts-1cf8l1j5qcim3 --output-template-file packaged-template.yaml
artifacts:
  files:
    - deployTemplate.yaml